### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by NazarZZ** [NazarZZ/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Liza1008** [comment]
Hey! My name is Nazar, and I got a bachelor's degree in software development. For the last two years, I have been creating various applications on the .NET platform. I want to improve my knowledge and get new ones. I am also fond of system administration and can repair almost everything in the world.

**Comment by NazarZZ** [comment]
Thanks!
