### ISSUE TITLE
Скласти блок контактної інформації.

### ISSUE THREAD

**Issue by NazarZZ** [NazarZZ/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by nazarr-zhuk** [comment]
**Nazar Zhuk**

Facebook:
- https://www.facebook.com/nazar.zhuk.3

Instagram:
- https://www.instagram.com/nazar_zz/

Skype:
- live:zhuk-nazar

Telegram:

- @Nazar_ZZ

E-mail:

- nazik.zhuk@gmail.com

GitHub:

- https://github.com/nazarZZ

Phone:

- +38 (063) 880 09 43

**Comment by nazarr-zhuk** [comment]
### Nazar Zhuk

**Facebook:**
- https://www.facebook.com/nazar.zhuk.3

**Skype:**
- live:zhuk-nazar

**Telegram:**
- @Nazar_ZZ

**E-mail:**
- nazik.zhuk@gmail.com

**GitHub:**
- https://github.com/nazarZZ

**Phone:**
- +38 (063) 880 09 43
